"""removed email column from Post table

Revision ID: 336d1a2a734f
Revises: ec955dde6019
Create Date: 2021-04-28 11:34:12.292772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336d1a2a734f'
down_revision = 'ec955dde6019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
