"""added image column in Product model

Revision ID: 73df685ab11b
Revises: 593f13ebe33a
Create Date: 2021-04-29 14:13:49.414205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73df685ab11b'
down_revision = '593f13ebe33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
